export interface SeedProductData {
  name: string;
  category: string;
  subcategory?: string;
  price: number;
  stock: number;
  imageUrl: string;
  description?: string;
  color?: string;
  size?: string;
}

const DEFAULT_DESCRIPTION = 'Imported from static frontend catalogue.';

export const seedProducts: SeedProductData[] = [
  // Home page – New Arrivals
  {
    name: 'Wool Blend Coat',
    category: 'Lifestyle',
    subcategory: 'New Arrivals',
    price: 179.95,
    stock: 75,
    imageUrl: '/images/2.jpg',
    description: DEFAULT_DESCRIPTION,
  },
  {
    name: 'Soft Knit Sweater',
    category: 'Lifestyle',
    subcategory: 'New Arrivals',
    price: 89.95,
    stock: 75,
    imageUrl: '/images/6.jpg',
    description: DEFAULT_DESCRIPTION,
  },
  {
    name: 'Sandalwood Candle',
    category: 'Lifestyle',
    subcategory: 'New Arrivals',
    price: 29.95,
    stock: 75,
    imageUrl: '/images/3.jpg',
    description: DEFAULT_DESCRIPTION,
  },
  {
    name: 'Rattan Storage Box',
    category: 'Lifestyle',
    subcategory: 'New Arrivals',
    price: 39.95,
    stock: 75,
    imageUrl: '/images/4.jpg',
    description: DEFAULT_DESCRIPTION,
  },
  {
    name: 'Amber Eau de Toilette',
    category: 'Lifestyle',
    subcategory: 'New Arrivals',
    price: 49.95,
    stock: 75,
    imageUrl: '/images/5.jpg',
    description: DEFAULT_DESCRIPTION,
  },
  {
    name: 'Linen Blend Shirt',
    category: 'Lifestyle',
    subcategory: 'New Arrivals',
    price: 69.95,
    stock: 75,
    imageUrl: '/images/1.jpg',
    description: DEFAULT_DESCRIPTION,
  },
  {
    name: 'Minimal Desk Lamp',
    category: 'Lifestyle',
    subcategory: 'New Arrivals',
    price: 120.0,
    stock: 75,
    imageUrl: '/images/d1.jpg',
    description: DEFAULT_DESCRIPTION,
  },
  {
    name: 'Weekender Tote',
    category: 'Lifestyle',
    subcategory: 'New Arrivals',
    price: 95.5,
    stock: 75,
    imageUrl: '/images/d2.jpg',
    description: DEFAULT_DESCRIPTION,
  },
  {
    name: 'Quilted Duvet Set',
    category: 'Lifestyle',
    subcategory: 'New Arrivals',
    price: 149.99,
    stock: 75,
    imageUrl: '/images/d3.png',
    description: DEFAULT_DESCRIPTION,
  },
  {
    name: 'Calming Diffuser',
    category: 'Lifestyle',
    subcategory: 'New Arrivals',
    price: 44.25,
    stock: 75,
    imageUrl: '/images/d4.jpg',
    description: DEFAULT_DESCRIPTION,
  },
  {
    name: 'Compact Vanity Mirror',
    category: 'Lifestyle',
    subcategory: 'New Arrivals',
    price: 58.0,
    stock: 75,
    imageUrl: '/images/d5.jpg',
    description: DEFAULT_DESCRIPTION,
  },

  // Home page – Best Sellers
  {
    name: 'Minimal Backpack',
    category: 'Lifestyle',
    subcategory: 'Best Sellers',
    price: 99.95,
    stock: 60,
    imageUrl: '/images/4.jpg',
    description: DEFAULT_DESCRIPTION,
  },
  {
    name: 'Cashmere Scarf',
    category: 'Lifestyle',
    subcategory: 'Best Sellers',
    price: 59.95,
    stock: 60,
    imageUrl: '/images/2.jpg',
    description: DEFAULT_DESCRIPTION,
  },
  {
    name: 'Essential Desk Set',
    category: 'Lifestyle',
    subcategory: 'Best Sellers',
    price: 45.5,
    stock: 60,
    imageUrl: '/images/d1.jpg',
    description: DEFAULT_DESCRIPTION,
  },
  {
    name: 'Stoneware Tea Set',
    category: 'Lifestyle',
    subcategory: 'Best Sellers',
    price: 74.0,
    stock: 60,
    imageUrl: '/images/5.jpg',
    description: DEFAULT_DESCRIPTION,
  },
  {
    name: 'Classic Bathrobe',
    category: 'Lifestyle',
    subcategory: 'Best Sellers',
    price: 120.0,
    stock: 60,
    imageUrl: '/images/d3.png',
    description: DEFAULT_DESCRIPTION,
  },
  {
    name: 'Travel Tote',
    category: 'Lifestyle',
    subcategory: 'Best Sellers',
    price: 85.75,
    stock: 60,
    imageUrl: '/images/d2.jpg',
    description: DEFAULT_DESCRIPTION,
  },
  {
    name: 'Warm Throw Blanket',
    category: 'Lifestyle',
    subcategory: 'Best Sellers',
    price: 64.5,
    stock: 60,
    imageUrl: '/images/d4.jpg',
    description: DEFAULT_DESCRIPTION,
  },
  {
    name: 'Scented Oil Set',
    category: 'Lifestyle',
    subcategory: 'Best Sellers',
    price: 34.75,
    stock: 60,
    imageUrl: '/images/d5.jpg',
    description: DEFAULT_DESCRIPTION,
  },

  // Men – Coats & Jackets
  {
    name: "Men's Padded Hooded Jacket",
    category: 'Men',
    subcategory: 'Coats & Jackets',
    price: 99.95,
    stock: 80,
    imageUrl: '/images/1.jpg',
    description: DEFAULT_DESCRIPTION,
    color: '#2E312F, #BEBFC4, #D9D6D0',
  },
  {
    name: "Men's Kapok Blend Corduroy Collar Jacket",
    category: 'Men',
    subcategory: 'Coats & Jackets',
    price: 79.95,
    stock: 80,
    imageUrl: '/images/d2.jpg',
    description: DEFAULT_DESCRIPTION,
    color: '#CEC0A6, #6F6353, #1E1C1A',
  },
  {
    name: "Men's Kapok Blend Corduroy Chore Jacket",
    category: 'Men',
    subcategory: 'Coats & Jackets',
    price: 79.95,
    stock: 80,
    imageUrl: '/images/d1.jpg',
    description: DEFAULT_DESCRIPTION,
    color: '#3E3023, #C9C1B7',
  },
  {
    name: "Men's Brushed Flannel Shirt Jacket",
    category: 'Men',
    subcategory: 'Coats & Jackets',
    price: 49.95,
    stock: 80,
    imageUrl: '/images/d4.jpg',
    description: DEFAULT_DESCRIPTION,
    color: '#1A1C1F, #676C70',
  },
  {
    name: "Men's Wool Blend Mac Coat",
    category: 'Men',
    subcategory: 'Coats & Jackets',
    price: 129.0,
    stock: 80,
    imageUrl: '/images/6.jpg',
    description: DEFAULT_DESCRIPTION,
    color: '#1F2327, #8A8D91',
  },
  {
    name: "Men's Water Repellent Parka",
    category: 'Men',
    subcategory: 'Coats & Jackets',
    price: 119.95,
    stock: 80,
    imageUrl: '/images/d3.png',
    description: DEFAULT_DESCRIPTION,
    color: '#4A4D46, #D9D8D0',
  },
  {
    name: "Men's Light Down Jacket",
    category: 'Men',
    subcategory: 'Coats & Jackets',
    price: 89.95,
    stock: 80,
    imageUrl: '/images/2.jpg',
    description: DEFAULT_DESCRIPTION,
    color: '#3C403F, #D4D4D6',
  },
  {
    name: "Men's Fleece Lined Coach Jacket",
    category: 'Men',
    subcategory: 'Coats & Jackets',
    price: 84.5,
    stock: 80,
    imageUrl: '/images/d5.jpg',
    description: DEFAULT_DESCRIPTION,
    color: '#1F1E21, #B7B5AF',
  },
  {
    name: "Men's Stretch Twill Jacket",
    category: 'Men',
    subcategory: 'Coats & Jackets',
    price: 74.95,
    stock: 80,
    imageUrl: '/images/4.jpg',
    description: DEFAULT_DESCRIPTION,
    color: '#403D3A, #D7D2C7',
  },
  {
    name: "Men's Overshirt in Wool",
    category: 'Men',
    subcategory: 'Coats & Jackets',
    price: 69.95,
    stock: 80,
    imageUrl: '/images/5.jpg',
    description: DEFAULT_DESCRIPTION,
    color: '#221E1E, #8F7E6B',
  },
  {
    name: "Men's Hybrid Down Short Coat",
    category: 'Men',
    subcategory: 'Coats & Jackets',
    price: 149.95,
    stock: 80,
    imageUrl: '/images/3.jpg',
    description: DEFAULT_DESCRIPTION,
    color: '#2A2B2A, #4C4E4A',
  },
  {
    name: "Men's Water Resistant Blazer",
    category: 'Men',
    subcategory: 'Coats & Jackets',
    price: 139.95,
    stock: 80,
    imageUrl: '/images/2.jpg',
    description: DEFAULT_DESCRIPTION,
    color: '#191A1C, #6E6F72',
  },

  // Women – Coats & Jackets
  {
    name: "Women's Cashmere Blend Coat",
    category: 'Women',
    subcategory: 'Coats & Jackets',
    price: 199.0,
    stock: 90,
    imageUrl: '/images/d4.jpg',
    description: DEFAULT_DESCRIPTION,
    color: '#E3D9CF, #443C37, #111111',
  },
  {
    name: "Women's Double Face Wool Coat",
    category: 'Women',
    subcategory: 'Coats & Jackets',
    price: 189.95,
    stock: 90,
    imageUrl: '/images/1.jpg',
    description: DEFAULT_DESCRIPTION,
    color: '#B8B2AA, #382E2E',
  },
  {
    name: "Women's Long Padded Parka",
    category: 'Women',
    subcategory: 'Coats & Jackets',
    price: 149.95,
    stock: 90,
    imageUrl: '/images/2.jpg',
    description: DEFAULT_DESCRIPTION,
    color: '#565C5B, #D7D4CD',
  },
  {
    name: "Women's Wool Tweed Jacket",
    category: 'Women',
    subcategory: 'Coats & Jackets',
    price: 129.95,
    stock: 90,
    imageUrl: '/images/3.jpg',
    description: DEFAULT_DESCRIPTION,
    color: '#3D3733, #CFC5B9',
  },
  {
    name: "Women's Light Down Vest",
    category: 'Women',
    subcategory: 'Coats & Jackets',
    price: 89.95,
    stock: 90,
    imageUrl: '/images/4.jpg',
    description: DEFAULT_DESCRIPTION,
    color: '#45403D, #ADA79B',
  },
  {
    name: "Women's Oversized Flannel Shirt Jacket",
    category: 'Women',
    subcategory: 'Coats & Jackets',
    price: 79.95,
    stock: 90,
    imageUrl: '/images/5.jpg',
    description: DEFAULT_DESCRIPTION,
    color: '#6B625C, #E6DED5',
  },
  {
    name: "Women's Ribbed Knit Cardigan",
    category: 'Women',
    subcategory: 'Coats & Jackets',
    price: 64.5,
    stock: 90,
    imageUrl: '/images/6.jpg',
    description: DEFAULT_DESCRIPTION,
    color: '#F2ECE5, #8B7C6A',
  },
  {
    name: "Women's Utility Field Jacket",
    category: 'Women',
    subcategory: 'Coats & Jackets',
    price: 109.95,
    stock: 90,
    imageUrl: '/images/d1.jpg',
    description: DEFAULT_DESCRIPTION,
    color: '#343934, #9DA48E',
  },
  {
    name: "Women's Water Repellent Trench",
    category: 'Women',
    subcategory: 'Coats & Jackets',
    price: 139.95,
    stock: 90,
    imageUrl: '/images/d2.jpg',
    description: DEFAULT_DESCRIPTION,
    color: '#CFBDA3, #4A4031',
  },
  {
    name: "Women's Linen Blend Blazer",
    category: 'Women',
    subcategory: 'Coats & Jackets',
    price: 119.0,
    stock: 90,
    imageUrl: '/images/d3.png',
    description: DEFAULT_DESCRIPTION,
    color: '#F1E7D4, #34312B',
  },
  {
    name: "Women's Textured Short Coat",
    category: 'Women',
    subcategory: 'Coats & Jackets',
    price: 129.95,
    stock: 90,
    imageUrl: '/images/d5.jpg',
    description: DEFAULT_DESCRIPTION,
    color: '#4D4B47, #B7B3AB',
  },
  {
    name: "Women's Brushed Wool Jacket",
    category: 'Women',
    subcategory: 'Coats & Jackets',
    price: 124.95,
    stock: 90,
    imageUrl: '/images/d4.jpg',
    description: DEFAULT_DESCRIPTION,
    color: '#2C2826, #C5B7AC',
  },

  // Beauty – Skincare Essentials
  {
    name: 'Light Toning Water - High Moisture',
    category: 'Beauty',
    subcategory: 'Skincare Essentials',
    price: 12.95,
    stock: 120,
    imageUrl: '/images/5.jpg',
    description: DEFAULT_DESCRIPTION,
    color: '#F6F2ED',
  },
  {
    name: 'Moisturising Milk',
    category: 'Beauty',
    subcategory: 'Skincare Essentials',
    price: 14.5,
    stock: 120,
    imageUrl: '/images/3.jpg',
    description: DEFAULT_DESCRIPTION,
    color: '#F1ECE7',
  },
  {
    name: 'Anti-Aging Essence',
    category: 'Beauty',
    subcategory: 'Skincare Essentials',
    price: 24.95,
    stock: 120,
    imageUrl: '/images/d1.jpg',
    description: DEFAULT_DESCRIPTION,
    color: '#F8F4EE, #D8C9B8',
  },
  {
    name: 'Mild Cleansing Oil',
    category: 'Beauty',
    subcategory: 'Skincare Essentials',
    price: 19.95,
    stock: 120,
    imageUrl: '/images/d2.jpg',
    description: DEFAULT_DESCRIPTION,
    color: '#F7F0E4, #E7D9C6',
  },
  {
    name: 'Face Soap - Moisture',
    category: 'Beauty',
    subcategory: 'Skincare Essentials',
    price: 7.95,
    stock: 120,
    imageUrl: '/images/d3.png',
    description: DEFAULT_DESCRIPTION,
    color: '#F9F4EA',
  },
  {
    name: 'Compressed Facial Cotton Sheet Mask (20 pack)',
    category: 'Beauty',
    subcategory: 'Skincare Essentials',
    price: 4.95,
    stock: 120,
    imageUrl: '/images/d4.jpg',
    description: DEFAULT_DESCRIPTION,
    color: '#F3E6DB',
  },
  {
    name: 'Organic Jojoba Oil',
    category: 'Beauty',
    subcategory: 'Skincare Essentials',
    price: 13.5,
    stock: 120,
    imageUrl: '/images/d5.jpg',
    description: DEFAULT_DESCRIPTION,
    color: '#FDF3E4, #E0C39F',
  },
  {
    name: 'Wooden Massage Brush',
    category: 'Beauty',
    subcategory: 'Skincare Essentials',
    price: 16.95,
    stock: 120,
    imageUrl: '/images/6.jpg',
    description: DEFAULT_DESCRIPTION,
    color: '#F6EADA, #BA9470',
  },
  {
    name: 'Gentle Foam Cleanser',
    category: 'Beauty',
    subcategory: 'Skincare Essentials',
    price: 9.95,
    stock: 120,
    imageUrl: '/images/4.jpg',
    description: DEFAULT_DESCRIPTION,
    color: '#F5EDE0',
  },
  {
    name: 'Botanical Sheet Mask Set (5 pack)',
    category: 'Beauty',
    subcategory: 'Skincare Essentials',
    price: 11.95,
    stock: 120,
    imageUrl: '/images/5.jpg',
    description: DEFAULT_DESCRIPTION,
    color: '#F4EBE1, #E1D1C0',
  },
  {
    name: 'Shea Butter Lip Balm',
    category: 'Beauty',
    subcategory: 'Skincare Essentials',
    price: 6.5,
    stock: 120,
    imageUrl: '/images/2.jpg',
    description: DEFAULT_DESCRIPTION,
    color: '#F4ECE0, #D4B8A0',
  },
  {
    name: 'Aromatherapy Bath Salts',
    category: 'Beauty',
    subcategory: 'Skincare Essentials',
    price: 15.95,
    stock: 120,
    imageUrl: '/images/1.jpg',
    description: DEFAULT_DESCRIPTION,
    color: '#F5E7D4, #C0A486',
  },
];
